you-get 'https://www.youtube.com/watch?v=u6Xd3kRHhJI'
you-get 'https://www.youtube.com/watch?v=rmGXek7qtVM'
you-get 'https://www.youtube.com/watch?v=OXaxZpgBMqc'
you-get 'https://www.youtube.com/watch?v=eAtcIoVGb-4'
you-get 'https://www.youtube.com/watch?v=4gGztYfp3ck'
you-get 'https://www.youtube.com/watch?v=u83WllUCLOc'
